// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krcvwrvdyqodmooynfrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyY3Z3cnZkeXFvZG1vb3luZnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTYzNjAsImV4cCI6MjA1OTE5MjM2MH0.ORcQ0pLayZ5j980mwqo10rP00YBMFOQ_SrEToDQ74zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);